# Generated by Django 5.2.7 on 2025-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyitem',
            old_name='type',
            new_name='property_type',
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
