# Generated by Django 5.2.7 on 2025-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_rename_type_propertyitem_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='area_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('mortgage', 'Mortgage / Guarantee'), ('other', 'Other')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
