# Generated by Django 5.2.7 on 2025-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_propertyitem_area_name_propertyitem_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('mortgage', 'Mortgage / Grawi'), ('other', 'Other')], default='sale', max_length=20),
        ),
    ]
