# Generated by Django 5.2.7 on 2025-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_remove_propertyitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyitem',
            name='price',
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='mortgage_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='rent_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='rent_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
