# Generated by Django 5.2.7 on 2025-10-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_remove_propertyitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('mortgage', 'Mortgage / Grawi')], max_length=20)),
                ('deal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('commission_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.propertyitem')),
            ],
        ),
    ]
