# Generated by Django 5.2.7 on 2025-10-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('mortgaged', 'Mortgaged'), ('pending', 'Pending / In Process')], default='available', max_length=20),
        ),
    ]
