# Generated by Django 5.2.7 on 2025-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_alter_propertyitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='kitchens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='parking_spaces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
