# Generated by Django 5.2.7 on 2025-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_propertyitem_bathrooms_propertyitem_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyitem',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='propertyitem',
            name='floors',
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Bedrooms / main rooms', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bathrooms', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='description',
            field=models.TextField(blank=True, help_text='Notes, special features, nearby bazar, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='kitchens',
            field=models.PositiveIntegerField(blank=True, help_text='Number of kitchens', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total mortgage / grawi amount', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='mortgage_terms',
            field=models.TextField(blank=True, help_text='Mortgage terms / duration / release conditions', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Parking / garage spots', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advance / security deposit', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='size',
            field=models.CharField(blank=True, help_text='Size in Biswa', max_length=50, null=True),
        ),
    ]
