# Generated by Django 5.2.7 on 2025-10-28 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_remove_propertyitem_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyitem',
            name='kitchens',
        ),
        migrations.RemoveField(
            model_name='propertyitem',
            name='parking_spaces',
        ),
        migrations.RemoveField(
            model_name='propertyitem',
            name='rooms',
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='floor_area_sqft',
            field=models.CharField(blank=True, help_text='Covered area (sq ft / marla / etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='floor_no',
            field=models.CharField(blank=True, help_text='e.g. Ground, 1st Floor, 2nd Floor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='mortgage_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='property_type',
            field=models.CharField(default='House', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
