# Generated by Django 5.2.7 on 2025-10-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_remove_propertyitem_kitchens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='kitchens',
            field=models.PositiveIntegerField(blank=True, help_text='How many kitchens?', null=True),
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='How many car parking slots?', null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='floor_no',
            field=models.CharField(blank=True, help_text='Which floor is THIS unit on? e.g. Ground, 1st, 2nd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, help_text='Total floors in the building', null=True),
        ),
    ]
