# Generated by Django 5.2.7 on 2025-10-28 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_propertyitem_kitchens_propertyitem_parking_spaces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='contact',
        ),
        migrations.AddField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='id_document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('partner', 'Partner / Investor'), ('client', 'Client / Buyer'), ('other', 'Other')], default='partner', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
