# Generated by Django 5.2.7 on 2025-10-28 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_rename_name_investor_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('purchase', 'Property Purchase / Payment to Owner'), ('maintenance', 'Repair / Maintenance / Work'), ('commission', 'Broker / Dealer Commission Paid'), ('legal', 'Documents / Legal / Transfer'), ('office', 'Office / Fuel / Travel'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property_item', models.ForeignKey(blank=True, help_text='Related property (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.propertyitem')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('sale', 'Property Sale / Installment Received'), ('rent', 'Rental Income'), ('investor_return', 'Paid Back by Buyer / Investor Return'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property_item', models.ForeignKey(blank=True, help_text='Related property (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealer.propertyitem')),
            ],
        ),
    ]
