# Generated by Django 5.2.6 on 2025-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0013_alter_investor_created_at_alter_investor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy / Money Spent'), ('sell', 'Sell / Money Received')], max_length=10),
        ),
    ]
